import { defineConfig } from '../models';

export default defineConfig({
  defaultBase: {
    name: 'Talent',
  },
  tables: [
    {
      name: 'REQs',
      focusColumns: [
        'Calculated Project Link',
        'Calculated Project',
        'Client Name (from SOW)',
        'Client',
        'Days Open',
        'Department Name',
        'Department',
        'Entity Name (from Divisions) (from Department) (from SOW)',
        'Entity',
        'Filled by',
        'Hiring Manager',
        'Late Stage Candidate Email',
        'Late Stage Candidate Lever Link',
        'Late Stage Candidate Name',
        'Late Stage Candidate',
        'Name (from Hiring Manager)',
        'Name (from Role Level) (from Resourcing)',
        'Open Date',
        'Picture (from Hiring Manager)',
        'Pipeline (from Role)',
        'Pipeline Name (from Role)',
        'Planned Start Date',
        'Project Name',
        'Project',
        'REQ Details',
        'REQ Number',
        'REQ',
        'Recruitment Lead Name',
        'Recruitment Lead Photo Url',
        'Recruitment Lead',
        'Requested by',
        'Required Start',
        'Role Level Override',
        'Role Name',
        'Role',
        'SOW',
        'Signup Info',
        'Status',
        'TZ Alignment Override',
        'dealName (from SOW)',
        'dealid (from SOW)',
      ],
      columnNameToObjectPropertyMapper: {
        ['REQ']: 'reqName',
        ['TZ Alignment Override']: 'timezoneAlignment',
        ['Role Name']: 'role.name',
        ['Pipeline (from Role)']: 'role.pipelineId',
        ['Department']: 'sow.departmentId',
        ['Client']: 'sow.clientId',
        ['Entity']: 'sow.entityId',
        ['Entity Name (from Divisions) (from Department) (from SOW)']:
          'sow.entityName',
      },
    },
  ],
});
