import { defineConfig } from '../models';

export default defineConfig({
  defaultBase: {
    name: 'Talent',
  },
  tables: [
    {
      name: 'REQs',
      focusColumns: [
        'Calculated Project Link',
        'Calculated Project',
        'Client Name (from SOW)',
        'Client',
        'Days Open',
        'Department Name',
        'Department',
        'Entity Name (from Divisions) (from Department) (from SOW)',
        'Entity',
        'Filled by',
        'Hiring Manager',
        'Late Stage Candidate Email',
        'Late Stage Candidate Lever Link',
        'Late Stage Candidate Name',
        'Late Stage Candidate',
        'Name (from Hiring Manager)',
        'Name (from Role Level) (from Resourcing)',
        'Open Date',
        'Picture (from Hiring Manager)',
        'Pipeline (from Role)',
        'Pipeline Name (from Role)',
        'Planned Start Date',
        'Project Name',
        'Project',
        'REQ Details',
        'REQ Number',
        'REQ',
        'Recruitment Lead Name',
        'Recruitment Lead Photo Url',
        'Recruitment Lead',
        'Requested by',
        'Required Start',
        'Role Level Override',
        'Role Name',
        'Role',
        'SOW',
        'Signup Info',
        'Status',
        'TZ Alignment Override',
        'dealName (from SOW)',
        'dealid (from SOW)',
      ],
      columnNameToObjectPropertyMapper: {
        ['REQ']: 'reqName',
        ['TZ Alignment Override']: 'timezoneAlignment',
        ['Role Name']: 'role.name',
        ['Pipeline (from Role)']: 'role.pipelineId',
        ['Department']: 'sow.departmentId',
        ['Client']: 'sow.clientId',
        ['Entity']: 'sow.entityId',
        ['Entity Name (from Divisions) (from Department) (from SOW)']:
          'sow.entityName',
      },
    },
    {
      name: 'Signups',
      focusColumns: [
        'Legal First Name',
        'Legal Middle Name',
        'Legal Last Name',
        'Preferred First Name',
        'Preferred Last Name',
        'Street Address',
        'Address Line 2',
        'City',
        'Postal Code',
        'Country',
        'State/Province',
        'Authorized to work',
        'Mailing Address Is Different',
        'Mailing Address',
        'Mailing Address 2',
        'Mailing City',
        'Mailing Postal Code',
        'Mailing Country',
        'Mailing Country State/Province',
        'Email',
        'Phone Number',
        'Tax ID',
        'Computer Election',
        'Computer Type',
        'Computer Size',
        'Computer Shipping Address Is Different',
        'Computer Shipping Address',
        'Computer Shipping Address 2',
        'Computer Shipping City',
        'Computer Shipping Postal Code',
        'Computer Shipping Country',
        'Computer Shipping Country State/Province',
        'Contract Witness Name',
        'Contract Witness Email',
        'Contract Type',
        'Company Name',
        'Company Tax ID',
        'Preferred Name',
        'Group',
        'Group Name',
        'Status',
        'Start Date',
        'Date Approved',
        'People List',
        'Team Member Type',
        'REQs',
        'REQ Names',
        'Target Account',
        'Compensation',
        'Currency',
        'Compensation Type',
        'Practical Payment Status',
        'LeverID',
        'Expiration Override',
        'Completed Practical',
        'Sign On Bonus Considerations',
        'Relocation Considerations',
        'Additional Notes',
        'Laptop Request Status',
        'State/Province Name',
        'Team Member Type Name',
        'Role',
        'Role Name',
        'HR Title (from Role)',
        'Target Account Name',
        'Expiration',
        'Offer Job Description (from Role)',
        'Completed Practical Name',
        'Calculated Mailing Address',
        'Country Name',
        'Country Code',
        'Recruiter',
        'Recruiter Name',
        'Recruiter Photo',
        'Late Stage Candidate (from REQs)',
        'Late Stage Candidate Name (from REQs)',
        'Late Stage Candidate Email (from REQs)',
        'Late Stage Candidate Lever Link (from REQs)',
        'Entity Name (from Divisions) (from Department) (from SOW) (from REQs)',
        'Direct Manager',
        'Name (from Direct Manager)',
        'Picture (from Direct Manager)',
        'Candidate Provided Information',
        'Lever Report',
        'name (from Lever Report)',
        'email (from Lever Report)',
        'lever-link (from Lever Report)',
      ],
    },
  ],
});
