import { defineConfig } from '../models';

export default defineConfig({
  defaultBase: {
    name: 'Talent',
  },
  tables: [
    {
      name: 'Assignments',
      focusColumns: [
        'Name',
        'Role',
        'Role Name (from Role)',
        'Role Name (from Role) (from Position)',
        'Team Member',
        'SOW',
        'Start Date',
        'End Date',
        'Project (from SOW)',
        'Timing Allocation',
        'Billing Allocation',
        'Resourcing Status',
        'Position',
        'Name (from Position)',
        'Role (from Position)',
        'Project',
        'ID',
        'REQ',
        'Entity',
      ],
      columnNameToObjectPropertyMapper: {
        'Project (from SOW)': 'sow.projectId',
        'Role (from Position)': 'position.roleId',
        ID: 'generatedResourcingNumber',
      },
    },
    {
      name: 'Positions',
    },
    {
      name: 'People List',
      alias: 'Team Members',
      focusColumns: [
        'Name',
        'Legal Name',
        'Lever Opportunity ID',
        'Apply Date',
        'Offer Date',
        'Join Date',
        'Exit Date',
        'Email',
        'Slack UID',
        'Slack Handle',
        'Team Member Type',
        'Current Role',
        'Current Role Name',
        'Department Name',
        'Starting Role',
        'Hiring Recruiter',
        'Starting Project',
        'Hiring Source Mech',
        'Hiring Source',
        'Pipelines',
        'Lever Report',
        'Rejected Offer',
        'Hiring Manager',
        'Current Manager',
        'Country',
        'Country Name',
        'Continent Name',
        'State/province',
        'State/Province Name',
        'Timezone Offset',
        'Timezone Label',
        'Gender',
        'Namely Profile ID',
        'Status',
        'Topology Permission Codes',
        'Topology Permission Exclude Codes',
        'SOWs',
        'Picture',
        'Github Username',
        'Active Team Member Utilization',
        'Active Billing Allocations',
        'Practice Area',
        'Practice Area Name',
        'HR Title',
        'Billable',
        'Project Count',
        'Project Names',
        'Active Project Count',
      ],
      columnNameToObjectPropertyMapper: {
        Country: {
          prefersSingleRecordLink: true,
        },
        'State/province': 'state',
      },
      views: ['Current Team', 'All Team Members', 'Alumni', 'Bench'],
    },
    {
      name: 'Resourcing',
      alias: 'Team Assignments',
      focusColumns: [
        'Slot',
        'Project Role',
        'Team Member',
        'Resource Start',
        'Resource End',
        'Project Override',
        'SOW',
        'Allocation',
        'Status',
        'Calculated Project',
        'Resource Number Generate',
        'Project from SOW',
        'REQs',
        'Entity',
      ],
      columnNameToObjectPropertyMapper: {
        'Resource Number Generate': 'generatedResourcingNumber',
        'Project from SOW': {
          prefersSingleRecordLink: true,
          propertyName: 'sow.projectId',
        },
        REQs: {
          propertyName: 'req',
          prefersSingleRecordLink: true,
        },
      },
    },
  ],
});
