export const MANAGE_ENTITIES_PERMISSION = 'MANAGE_ENTITIES';
export const CREATE_ENTITY_PERMISSION = 'CREATE_ENTITY';
export const VIEW_ENTITIES_PERMISSION = 'VIEW_ENTITIES';
export const COUNT_ENTITIES_PERMISSION = 'COUNT_ENTITIES';
export const VIEW_ENTITY_DETAILS_PERMISSION = 'VIEW_ENTITY_DETAILS';
export const UPDATE_ENTITY_PERMISSION = 'UPDATE_ENTITY';
export const DELETE_ENTITY_PERMISSION = 'DELETE_ENTITY';
